import type { CodegenStep } from '../types';
import type { CandidateScore, RankedElementScore, ResolvedResolverConfig, StepSignalAttributes } from './types';
export declare function getElementDepth(element: Element): number;
export declare function getDescendantCount(element: Element): number;
export declare function buildScopeElements(snapshot: Document, selector?: string | null): Set<Element>;
export declare function isDescendantOfAnyScope(element: Element, scopes: Set<Element>): boolean;
export declare function textMatchStrength(element: Element, step: CodegenStep): number;
export declare function attributeMatchStrength(element: Element, step: CodegenStep): number;
export declare function localityStrength(element: Element): number;
export declare function parentProximityStrength(element: Element, snapshot: Document, step: CodegenStep): number;
export declare function fastPruneMatchedElements(matches: Element[], snapshot: Document, step?: CodegenStep): Element[];
export declare function scoreMatchedElements(matches: Element[], snapshot: Document, step?: CodegenStep): RankedElementScore[];
export declare function enrichSignalAttributesFromElement(attrs: StepSignalAttributes, element: Element): void;
export declare function findSeedElements(step: CodegenStep, snapshot: Document): Element[];
export declare function isOverlyBroadSeedElement(element: Element): boolean;
export declare function containsCalendarHint(value?: string | null): boolean;
export declare function tokenizeIntentText(value: string): string[];
export declare function intentTokensForStep(step: CodegenStep): string[];
export declare function hasCalendarIntent(step: CodegenStep): boolean;
export declare function isCalendarContext(step: CodegenStep, snapshot: Document, attrs: StepSignalAttributes, seedElements: Element[]): boolean;
export declare function getCalendarScopeSelectors(step: CodegenStep, attrs: StepSignalAttributes): string[];
export declare function extractCalendarTextTarget(step: CodegenStep, textExcerpt?: string | null): string | null;
export declare function looksDateValue(value?: string): boolean;
export type IntentActionHint = 'click' | 'input' | 'submit' | 'custom-control-open' | 'custom-select' | 'custom-menu-select' | 'hover' | 'scroll' | 'navigate' | 'unknown';
export interface IntentScore {
    score: number;
    tokenScore: number;
    roleScore: number;
    tagScore: number;
    matchedTokens: string[];
    tokens: string[];
    actionHint: IntentActionHint;
}
export declare function evaluateIntentMatch(el: Element, step: CodegenStep): IntentScore;
export declare function selectorLooksInputLike(selector: string): boolean;
export declare function selectorLooksInteractive(selector: string): boolean;
export declare function elementLooksInputLike(el: Element | null): boolean;
export declare function elementLooksInteractive(el: Element | null): boolean;
export declare function hasFieldIntent(step: CodegenStep): boolean;
export declare function getCandidateElement(snapshot: Document, selector: string): Element | null;
export declare function isLowScoreFallbackCandidateSafe(step: CodegenStep, snapshot: Document, candidate: CandidateScore, config: ResolvedResolverConfig): boolean;
export declare function matchesIntent(el: Element, intent: string | CodegenStep, defaultIntentMinScore: number): boolean;
