/**
 * packages/codegen/src/flow-review.utils.ts
 *
 * Pure utility functions for the FlowReview presentation layer.
 * Zero side effects. Zero DB access. Only imports type definitions.
 * Every function is independently testable.
 */
import type { SelectorQuality } from './flow-review.types';
/**
 * Extracts the pathname from a URL string.
 * Falls back to the raw input on parse failure.
 */
export declare function extractPathname(url: string): string;
/**
 * Normalizes a URL for page-grouping purposes.
 * Strips trailing slash (except root), query params, and hash.
 * "/dashboard/" and "/dashboard?tab=1" both normalize to "/dashboard".
 */
export declare function normalizeUrlForGrouping(url: string): string;
/**
 * Derives a human-readable page name from a URL.
 *
 * Rules (applied in order):
 *   1. Empty URL           → "Page N"
 *   2. Root path "/"       → "<DomainName> Root" (e.g. "Orangehrmlive Root")
 *   3. Non-root path       → title-case last 1-2 stable segments
 *      A "noisy" segment is: purely numeric, UUID-shaped, or ≤2 chars.
 *      If all segments are noisy → "Page N"
 *
 * @param url           Raw URL string from the step
 * @param visitIndex    1-based sequential visit number (used as fallback label)
 */
export declare function getPageName(url: string, visitIndex: number): string;
/**
 * Transforms a raw CodegenStep intent into a display-ready string.
 * Always returns a non-null string (best-effort).
 *
 * Input pattern from CodegenService:
 *   "{action}_{sanitized_selector_chars}"
 *   e.g. "click_data_testid_login_btn_"
 *        "input_input_name_username_"
 *        "click_html_body_div_3_form_button"
 *
 * Strategy:
 *   1. Strip leading action verb prefix ("click_", "input_", etc.)
 *   2. Remove noise tokens generated by selector sanitization
 *   3. Title-case and join remaining tokens
 *   4. If nothing meaningful remains, fall back to "<Verb> Element"
 *   5. Cap at 40 characters
 */
export declare function humanizeIntent(intent: string, action: string): string;
/**
 * Maps an ActionType to a user-facing verb.
 * e.g. 'input' → 'Type', 'custom-select' → 'Select'
 */
export declare function normalizeActionVerb(action: string): string;
/**
 * Maps a SelectorPriority string to a SelectorQuality reliability tier.
 * 'unknown' is already returned by normalizeSelectorPriority() for anything
 * unrecognized (including the multi-attribute P8.5 "multi-attribute" priority
 * that doesn't exist in the SelectorPriority enum).
 */
export declare function getSelectorQuality(priority: string): SelectorQuality;
/**
 * Returns a display-ready confidence label.
 *
 * The ambiguous case: sampleSize === 1 && confidence === 1.0
 *   This can mean either "seen once, Laplace gives 1.0" OR "no edge found,
 *   both defaulted to 1.0". We cannot distinguish these from CodegenStep
 *   data alone, so we surface it honestly as "unverified".
 */
export declare function getConfidenceLabel(confidence: number, sampleSize: number): string;
/**
 * Produces a display-safe version of a step value.
 * - '<LLM_GENERATE_MOCK_DATA>' → '{auto-generated}'
 * - Password-intent fields     → '••••••••'
 * - Email addresses            → 'j***@example.com'
 * - All other values           → returned as-is
 */
export declare function maskDisplayValue(value: string, intent?: string): string;
/**
 * Derives a human-readable flow title combining the site domain and an
 * inferred flow type.
 *
 * Examples:
 *   URL: "https://app.orangehrmlive.com/auth/login"
 *   Intents containing "login", "password" → "Orangehrmlive — Login Flow"
 *
 *   URL: "https://shop.example.com/checkout"
 *   Intents containing "checkout", "payment" → "Example — Checkout Flow"
 *
 * Falls back gracefully:
 *   - No parseable URL             → just flowType
 *   - No recognizable intent type  → recorded page title stripped of " - SiteName"
 *   - No title either              → "Recorded Flow"
 */
export declare function deriveFlowTitle(url: string, recordedTitle: string, steps: ReadonlyArray<{
    intent: string;
}>): string;
