/**
 * packages/codegen/src/flow-review.utils.ts
 *
 * Pure utility functions for the FlowReview presentation layer.
 * Zero side effects. Zero DB access. Only imports type definitions.
 * Every function is independently testable.
 */

import type { SelectorQuality } from './flow-review.types';

// ─────────────────────────────────────────────────────────────────────────────
// URL HELPERS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Extracts the pathname from a URL string.
 * Falls back to the raw input on parse failure.
 */
export function extractPathname(url: string): string {
  if (!url) return '/';
  try {
    return new URL(url).pathname;
  } catch {
    return url;
  }
}

/**
 * Normalizes a URL for page-grouping purposes.
 * Strips trailing slash (except root), query params, and hash.
 * "/dashboard/" and "/dashboard?tab=1" both normalize to "/dashboard".
 */
export function normalizeUrlForGrouping(url: string): string {
  if (!url) return '';
  try {
    const parsed = new URL(url);
    const pathname = parsed.pathname.replace(/\/$/, '') || '/';
    return parsed.origin + pathname;
  } catch {
    // Relative URL or unparseable — strip trailing slash at least
    return url.replace(/\?.*$/, '').replace(/#.*$/, '').replace(/\/$/, '') || url;
  }
}

/**
 * Derives a human-readable page name from a URL.
 *
 * Rules (applied in order):
 *   1. Empty URL           → "Page N"
 *   2. Root path "/"       → "<DomainName> Root" (e.g. "Orangehrmlive Root")
 *   3. Non-root path       → title-case last 1-2 stable segments
 *      A "noisy" segment is: purely numeric, UUID-shaped, or ≤2 chars.
 *      If all segments are noisy → "Page N"
 *
 * @param url           Raw URL string from the step
 * @param visitIndex    1-based sequential visit number (used as fallback label)
 */
export function getPageName(url: string, visitIndex: number): string {
  if (!url) return `Page ${visitIndex}`;

  let pathname = '';
  let hostname = '';

  try {
    const parsed = new URL(url);
    pathname = parsed.pathname;
    hostname = parsed.hostname;
  } catch {
    // Treat the raw string as a pathname
    pathname = url;
  }

  // Root path — derive from hostname
  if (pathname === '/' || pathname === '') {
    if (hostname) {
      const domain = hostname.replace(/^www\./, '').split('.')[0];
      return titleCase(domain) + ' Root';
    }
    return `Page ${visitIndex}`;
  }

  // Extract stable path segments
  const segments = pathname.split('/').filter(Boolean);
  const stable = segments.filter(s => !isNoisySegment(s));

  if (stable.length === 0) return `Page ${visitIndex}`;

  // Use last two stable segments for specificity
  const label = stable
    .slice(-2)
    .map(s => s.replace(/[-_]/g, ' '))
    .map(titleCase)
    .join(' ');

  return label || `Page ${visitIndex}`;
}

/**
 * Returns true for path segments that represent IDs, not semantic page names.
 * Examples: "123", "a3f2b1c4-...", "ph" (2 chars)
 */
function isNoisySegment(segment: string): boolean {
  if (segment.length <= 2) return true;
  if (/^\d+$/.test(segment)) return true;
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-/.test(segment)) return true;
  return false;
}

// ─────────────────────────────────────────────────────────────────────────────
// INTENT HUMANIZATION
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Transforms a raw CodegenStep intent into a display-ready string.
 * Always returns a non-null string (best-effort).
 *
 * Input pattern from CodegenService:
 *   "{action}_{sanitized_selector_chars}"
 *   e.g. "click_data_testid_login_btn_"
 *        "input_input_name_username_"
 *        "click_html_body_div_3_form_button"
 *
 * Strategy:
 *   1. Strip leading action verb prefix ("click_", "input_", etc.)
 *   2. Remove noise tokens generated by selector sanitization
 *   3. Title-case and join remaining tokens
 *   4. If nothing meaningful remains, fall back to "<Verb> Element"
 *   5. Cap at 40 characters
 */
export function humanizeIntent(intent: string, action: string): string {
  if (!intent) return normalizeActionVerb(action) + ' Element';

  // Strip the leading action verb prefix
  const prefixesToStrip = [
    'custom_select_', 'navigate_to_', 'custom-select_',
    'interact_', 'generic_', 'scroll_', 'hover_',
    'submit_', 'select_', 'click_', 'input_', 'type_',
  ];

  let remainder = intent;
  for (const prefix of prefixesToStrip) {
    if (remainder.startsWith(prefix)) {
      remainder = remainder.slice(prefix.length);
      break;
    }
  }

  // If nothing was stripped try splitting on the first underscore
  if (remainder === intent) {
    const firstUs = intent.indexOf('_');
    if (firstUs > 0) remainder = intent.slice(firstUs + 1);
  }

  // Tokens generated by selector sanitization that add no semantic value
  const NOISE: ReadonlySet<string> = new Set([
    'data', 'testid', 'test', 'id', 'name', 'class',
    'html', 'body', 'div', 'form', 'span', 'ul', 'li',
    'input', 'button', 'a', 'btn', 'el',
    'wrapper', 'container', 'component',
  ]);

  const parts = remainder
    .split('_')
    .map(t => t.trim())
    .filter(t => t.length > 0 && !NOISE.has(t.toLowerCase()));

  if (parts.length === 0) {
    return normalizeActionVerb(action) + ' Element';
  }

  const humanized = parts.map(titleCase).join(' ');
  return humanized.length > 40 ? humanized.slice(0, 37) + '…' : humanized;
}

/**
 * Maps an ActionType to a user-facing verb.
 * e.g. 'input' → 'Type', 'custom-select' → 'Select'
 */
export function normalizeActionVerb(action: string): string {
  const MAP: Record<string, string> = {
    click:          'Click',
    input:          'Type',
    submit:         'Submit',
    'custom-control-open': 'Open',
    'custom-select':'Select',
    'custom-menu-select': 'Select',
    scroll:         'Scroll',
    hover:          'Hover',
    navigate:       'Navigate',
  };
  return MAP[action] ?? titleCase(action);
}

// ─────────────────────────────────────────────────────────────────────────────
// SELECTOR QUALITY
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Maps a SelectorPriority string to a SelectorQuality reliability tier.
 * 'unknown' is already returned by normalizeSelectorPriority() for anything
 * unrecognized (including the multi-attribute P8.5 "multi-attribute" priority
 * that doesn't exist in the SelectorPriority enum).
 */
export function getSelectorQuality(priority: string): SelectorQuality {
  switch (priority) {
    case 'data-testid': return 'best';
    case 'id':
    case 'attribute':
    case 'text':        return 'good';
    case 'class':
    case 'path':
    case 'xpath':
    case 'other':
    case 'chained':     return 'fragile';
    default:            return 'unknown';
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// CONFIDENCE LABEL
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Returns a display-ready confidence label.
 *
 * The ambiguous case: sampleSize === 1 && confidence === 1.0
 *   This can mean either "seen once, Laplace gives 1.0" OR "no edge found,
 *   both defaulted to 1.0". We cannot distinguish these from CodegenStep
 *   data alone, so we surface it honestly as "unverified".
 */
export function getConfidenceLabel(confidence: number, sampleSize: number): string {
  if (sampleSize === 1 && Math.abs(confidence - 1.0) < 0.001) {
    return 'unverified';
  }
  const pct = Math.round(confidence * 100);
  if (confidence >= 0.9) return `${pct}%`;
  if (confidence >= 0.7) return `${pct}% (moderate)`;
  return `${pct}% (low)`;
}

// ─────────────────────────────────────────────────────────────────────────────
// VALUE MASKING
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Produces a display-safe version of a step value.
 * - '<LLM_GENERATE_MOCK_DATA>' → '{auto-generated}'
 * - Password-intent fields     → '••••••••'
 * - Email addresses            → 'j***@example.com'
 * - All other values           → returned as-is
 */
export function maskDisplayValue(value: string, intent?: string): string {
  if (value === '<LLM_GENERATE_MOCK_DATA>') return '{auto-generated}';

  const intentLower = (intent ?? '').toLowerCase();
  if (intentLower.includes('password') || intentLower.includes('secret')) {
    return '••••••••';
  }

  if (value.includes('@') && value.includes('.')) {
    const atIdx = value.indexOf('@');
    const local = value.slice(0, atIdx);
    const domain = value.slice(atIdx + 1);
    const maskedLocal = local.charAt(0) + '***';
    return `${maskedLocal}@${domain}`;
  }

  return value;
}

// ─────────────────────────────────────────────────────────────────────────────
// FLOW TITLE
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Derives a human-readable flow title combining the site domain and an
 * inferred flow type.
 *
 * Examples:
 *   URL: "https://app.orangehrmlive.com/auth/login"
 *   Intents containing "login", "password" → "Orangehrmlive — Login Flow"
 *
 *   URL: "https://shop.example.com/checkout"
 *   Intents containing "checkout", "payment" → "Example — Checkout Flow"
 *
 * Falls back gracefully:
 *   - No parseable URL             → just flowType
 *   - No recognizable intent type  → recorded page title stripped of " - SiteName"
 *   - No title either              → "Recorded Flow"
 */
export function deriveFlowTitle(
  url: string,
  recordedTitle: string,
  steps: ReadonlyArray<{ intent: string }>,
): string {
  let domain = '';
  try {
    const host = new URL(url).hostname.replace(/^www\./, '');
    domain = titleCase(host.split('.')[0]);
  } catch {
    /* ignore — domain stays '' */
  }

  const allIntents = steps.map(s => s.intent.toLowerCase()).join(' ');

  let flowType: string;
  if (allIntents.includes('login') || allIntents.includes('signin') || allIntents.includes('password')) {
    flowType = 'Login Flow';
  } else if (allIntents.includes('register') || allIntents.includes('signup')) {
    flowType = 'Registration Flow';
  } else if (allIntents.includes('checkout') || allIntents.includes('payment')) {
    flowType = 'Checkout Flow';
  } else if (allIntents.includes('search')) {
    flowType = 'Search Flow';
  } else if (recordedTitle) {
    // Strip the common " - SiteName" suffix from page titles
    flowType = recordedTitle.replace(/\s*[-|–|·]\s*.+$/, '').trim() || 'Recorded Flow';
  } else {
    flowType = 'Recorded Flow';
  }

  return domain ? `${domain} — ${flowType}` : flowType;
}

// ─────────────────────────────────────────────────────────────────────────────
// INTERNAL
// ─────────────────────────────────────────────────────────────────────────────

function titleCase(str: string): string {
  if (!str) return '';
  return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
}
