import type { BoundedFieldSelectorSpec, BoundedFieldStructuredSelectorSpec, EquivalentRendering, FlatSelectorEngine, FlatSelectorSpec, LabelContextSelectorSpec, ScopedSelectorSpec, SelectorPriority, SelectorProofLevel, SelectorSource, SelectorSpec, TriggerContextSelectorSpec } from './types';
export declare function inferSelectorEngine(selector: string | null | undefined, selectorPriority?: SelectorPriority | string): FlatSelectorEngine;
export declare function buildSelectorSpec(params: {
    selector: string;
    selectorPriority?: SelectorPriority | string;
    engine?: FlatSelectorEngine;
    source: SelectorSource;
    proofLevel: SelectorProofLevel;
    labelContext?: LabelContextSelectorSpec;
    triggerContext?: TriggerContextSelectorSpec;
    rank?: number;
    confidence?: number;
    rejectReason?: string | null;
    warningCodes?: string[] | null;
}): FlatSelectorSpec;
export declare function buildScopedSelectorSpec(params: {
    selector: string;
    scope: SelectorSpec;
    target: SelectorSpec;
    relation?: ScopedSelectorSpec['relation'];
    source: SelectorSource;
    proofLevel: SelectorProofLevel;
    rank?: number;
    confidence?: number;
    rejectReason?: string | null;
    warningCodes?: string[] | null;
}): ScopedSelectorSpec;
export declare function buildBoundedFieldSelectorSpec(params: {
    selector: string;
    boundedField: BoundedFieldSelectorSpec;
    source: SelectorSource;
    proofLevel: SelectorProofLevel;
    rank?: number;
    confidence?: number;
    rejectReason?: string | null;
    warningCodes?: string[] | null;
}): BoundedFieldStructuredSelectorSpec;
export declare function isSelectorSpecExactProofLevel(proofLevel: SelectorProofLevel | undefined): boolean;
export declare function isSelectorSpecRenderableAsNative(spec: SelectorSpec | undefined): boolean;
export declare function isEquivalentRenderingRenderable(rendering: EquivalentRendering | undefined): boolean;
export declare function canRenderSelectorSpecConfidently(spec: SelectorSpec | undefined): boolean;
export declare function getSelectorSpecRenderingWarnings(spec: SelectorSpec | undefined): string[];
export declare function pickPreferredEquivalentRendering(renderings: EquivalentRendering[] | undefined): EquivalentRendering | null;
export declare function renderLocatorExpressionFromSelectorSpec(spec: SelectorSpec | undefined): string | null;
export declare function renderLocatorExpressionFromEquivalentRendering(rendering: EquivalentRendering | undefined): string | null;
